# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux_build:
    name: Linux Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install Dependencies and Build Dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt pyinstaller
    - name: Build
      run: |
        cd src/
        pyinstaller \
          --name "Bible Notify" \
          --windowed --onedir \
          --add-data assets:assets \
          --icon assets/icon.ico \
          main.py
    - name: Upload the Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: Bible Notify
        path: "BibleNotify/dist/*"

  macos_build:
    name: macOS Build
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install Dependencies and Build Dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt pyinstaller
    - name: Build
      run: |
        cd src/
        pyinstaller \
          --name "Bible Notify" \
          --windowed --onedir \
          --add-data assets:assets \
          --icon assets/icon.ico \
          main.py
    - name: Upload the Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: Bible Notify
        path: "BibleNotify/dist/*"
  
  windows_build:
    name: Windows Build
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install Dependencies and Build Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt pyinstaller
    - name: Build
      run: |
        cd src/
        pyinstaller --name "Bible Notify" --windowed --onedir --add-data "assets;assets" --icon assets/icon.ico main.py
    - name: Upload the Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: Bible Notify
        path: "BibleNotify/dist/*"
